# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
# https://aws.amazon.com/blogs/compute/introducing-simplified-serverless-application-deplyoment-and-management/
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{cookiecutter.name}}
  {{cookiecutter.description}}
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # Properties of AWS::Serverless::Function
    Handler: lambda.handler
    Runtime: nodejs10.x
    CodeUri: ./dist
    #DeadLetterQueue:
    #Description:
    MemorySize: 256
    Timeout: 180
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-vpcconfig.html
    #VpcConfig:
    Environment:
      Variables:
        MyProp: MyVal
    #Tags:
    #Tracing:
    #KmsKeyArn:
    #Layers:
    #AutoPublishAlias:
    #DeploymentPreference:
    #PermissionsBoundary:
    #ReservedConcurrentExecutions:

Resources:

  {{cookiecutter.name}}Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction    
    Properties:
      Policies: AmazonDynamoDBFullAccess
      Events:
        WebRoot:
          Properties:
            Method: any
            Path: /
            RestApiId: !Ref {{cookiecutter.name}}Api
          Type: Api
        WebProxy:
          Properties:
            Method: any
            Path: /{web+}
            RestApiId: !Ref {{cookiecutter.name}}Api
          Type: Api   
        PetsGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/pets
            Method: get
            RestApiId: !Ref {{cookiecutter.name}}Api
        PetsGetById:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/pets/{petId}
            Method: get
            RestApiId: !Ref {{cookiecutter.name}}Api

  {{cookiecutter.name}}Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  {{cookiecutter.name}}Api:
    Description: "API Gateway endpoint URL for Prod stage for {{cookiecutter.name}}Api"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  {{cookiecutter.name}}Function:
    Description: "{{cookiecutter.name}}Function ARN"
    Value: !GetAtt {{cookiecutter.name}}Function.Arn
  {{cookiecutter.name}}Role:
    Description: "Implicit IAM Role created for {{cookiecutter.name}}Function function"
    Value: !GetAtt {{cookiecutter.name}}Role.Arn
