# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
# https://aws.amazon.com/blogs/compute/introducing-simplified-serverless-application-deplyoment-and-management/
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{cookiecutter.projectName}}
  {{cookiecutter.projectDescription}}
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # Properties of AWS::Serverless::Function
    Handler: build/lambda.handler
    Runtime: nodejs10.x
    CodeUri: ./api
    #DeadLetterQueue:
    #Description:
    MemorySize: 256
    Timeout: 180
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-vpcconfig.html
    #VpcConfig:
    Environment:
      Variables:
        MyProp: MyVal
    #Tags:
    #Tracing:
    #KmsKeyArn:
    #Layers:
    #AutoPublishAlias:
    #DeploymentPreference:
    #PermissionsBoundary:
    #ReservedConcurrentExecutions:

Resources:

  {{cookiecutter.functionName}}:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction    
    Properties:
      Policies: AmazonDynamoDBFullAccess
      Events:
        PetsGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pets
            Method: get
            RestApiId: !Ref {{cookiecutter.apiName}}
        PetsGetById:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pets/{petId}
            Method: get
            RestApiId: !Ref {{cookiecutter.apiName}}

  {{cookiecutter.apiName}}:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        openapi: "3.0.0"
        info:
          version: 1.0.0
          title: Swagger Petstore
          license:
            name: MIT
        servers:
          - url: http://petstore.swagger.io/v1
        paths:
          /pets:
            get:
              summary: List all pets
              operationId: listPets
              tags:
                - pets
              parameters:
                - name: limit
                  in: query
                  description: How many items to return at one time (max 100)
                  required: false
                  schema:
                    type: integer
                    format: int32
              responses:
                '200':
                  description: A paged array of pets
                  headers:
                    x-next:
                      description: A link to the next page of responses
                      schema:
                        type: string
                  content:
                    application/json:    
                      schema:
                        $ref: "#/components/schemas/Pets"
                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Error"
            post:
              summary: Create a pet
              operationId: createPets
              tags:
                - pets
              responses:
                '201':
                  description: Null response
                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Error"
          /pets/{petId}:
            get:
              summary: Info for a specific pet
              operationId: showPetById
              tags:
                - pets
              parameters:
                - name: petId
                  in: path
                  required: true
                  description: The id of the pet to retrieve
                  schema:
                    type: string
              responses:
                '200':
                  description: Expected response to a valid request
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Pets"
                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Error"
        components:
          schemas:
            Pet:
              required:
                - id
                - name
              properties:
                id:
                  type: integer
                  format: int64
                name:
                  type: string
                tag:
                  type: string
            Pets:
              type: array
              items:
                $ref: "#/components/schemas/Pet"
            Error:
              required:
                - code
                - message
              properties:
                code:
                  type: integer
                  format: int32
                message:
                  type: string

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  {{cookiecutter.apiName}}:
    Description: "API Gateway endpoint URL for Prod stage for {{cookiecutter.functionName}}"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  {{cookiecutter.functionName}}:
    Description: "{{cookiecutter.functionName}} ARN"
    Value: !GetAtt {{cookiecutter.functionName}}.Arn
  {{cookiecutter.roleName}}:
    Description: "Implicit IAM Role created for {{cookiecutter.functionName}} function"
    Value: !GetAtt {{cookiecutter.roleName}}.Arn
